spring:
  application:
    name: attendease-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  data:
    mongodb:
      auto-index-creation: true
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
      file-size-threshold: 2MB

server:
  port: 8082
  tomcat:
    max-swallow-size: 200MB
    max-http-form-post-size: 200MB
    max-http-header-size: 8KB
    connection-timeout: 60000
    threads:
      max: 200
      min-spare: 10
  max-http-request-header-size: 8KB

jwt:
  secret: ${JWT_SECRET}

# LOGGING CONFIGS
logging:
  level:
    org:
      springframework:
        data:
          mongodb: DEBUG
        messaging:
          simp:
            stomp: TRACE
        web:
          socket:
            messaging:
              StompSubProtocolHandler: TRACE
        boot:
          autoconfigure:
            web:
              servlet:
                MultipartAutoConfiguration: DEBUG
      mongodb:
        driver: INFO
    com:
      attendease:
        backend:
          configurations: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

info:
  timezone: ${user.timezone:UTC}
  application:
    name: ${spring.application.name}

# ACADEMIC CONFIGURATIONS
academic:
  year-level:
    min: 1
    max: 4
  semester:
    min: 1
    max: 2